# Generated by Django 5.0.3 on 2024-03-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
