# Generated by Django 5.0.3 on 2024-04-16 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_useraccount_follows"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
