# Generated by Django 5.0.3 on 2024-04-16 17:18

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_profile_user_remove_useraccount_follows_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_account_teste",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="profile_user",
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name=accounts.models.UserAccount
            ),
        ),
    ]
