# Generated by Django 5.0.3 on 2024-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_useraccount_follows_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
