# Generated by Django 5.0.3 on 2024-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
