# Generated by Django 5.0.3 on 2024-04-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_useraccount_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
