# Generated by Django 5.0.3 on 2024-04-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_post_quoted_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
