# Generated by Django 5.0.3 on 2024-04-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_post_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="bio",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="bio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
